import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Skyline Penthouse',
    location: 'Downtown Metro, Neo City',
    price: 1250000,
    image: 'https://picsum.photos/800/600?random=1',
    rentalYield: 5.2,
    appreciation: 8.5,
    beds: 3,
    baths: 2,
    sqft: 2100,
    type: 'Apartment',
    isTrending: true,
  },
  {
    id: '2',
    title: 'Eco-Smart Villa',
    location: 'Greenbelt District, Silicon Valley',
    price: 3400000,
    image: 'https://picsum.photos/800/600?random=2',
    rentalYield: 4.1,
    appreciation: 12.0,
    beds: 5,
    baths: 4,
    sqft: 4500,
    type: 'Villa',
  },
  {
    id: '3',
    title: 'Urban Loft',
    location: 'Arts District, Brooklyn',
    price: 850000,
    image: 'https://picsum.photos/800/600?random=3',
    rentalYield: 6.5,
    appreciation: 5.5,
    beds: 1,
    baths: 1,
    sqft: 950,
    type: 'Apartment',
  },
  {
    id: '4',
    title: 'Coastal Retreat',
    location: 'Malibu Coast, California',
    price: 5200000,
    image: 'https://picsum.photos/800/600?random=4',
    rentalYield: 3.8,
    appreciation: 9.2,
    beds: 4,
    baths: 3,
    sqft: 3200,
    type: 'House',
    isTrending: true,
  },
  {
    id: '5',
    title: 'Tech Hub Condo',
    location: 'Austin, Texas',
    price: 650000,
    image: 'https://picsum.photos/800/600?random=5',
    rentalYield: 7.1,
    appreciation: 10.5,
    beds: 2,
    baths: 2,
    sqft: 1100,
    type: 'Condo',
  },
  {
    id: '6',
    title: 'Modernist Cabin',
    location: 'Aspen, Colorado',
    price: 2100000,
    image: 'https://picsum.photos/800/600?random=6',
    rentalYield: 5.8,
    appreciation: 6.0,
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: 'House',
  },
];
